version: "3.8"

services:
  service-b:
    build:
      context: ./service-b
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - PORT=8080
    env_file:
      - .env
    networks:
      - weather-network
    container_name: service-b

  service-a:
    build:
      context: ./service-a
    ports:
      - "8081:8081"
    environment:
      - SERVICE_B_URL=http://service-b:8080
      - PORT=8081
    depends_on:
      - service-b
    networks:
      - weather-network
    container_name: service-a

networks:
  weather-network:
    driver: bridge
